libigl/libigl-python-bindings

setup.py

numpy and scipy should be marked as dependencies in `setup.py` via `install_requires`. The module cannot be compiled (numpy) or imported (numpy and scipy) without them.

Add numpy and scipy as a dependency

---

src/remove_duplicate_vertices.cpp

- Docs show that `f` is not required, but the bound function is called with it.  This might be optional there, but I haven't checked.
- Docs show returning three objects and then how to map new faces, but this is already done in the function, and they are returned (validated by `np.all(SVJ[f] == SF)`).

Update remove_duplicate_vertices docs to match the call signature and return

---

tutorial/index.md

Thank you for maintaining this nice library.
Just a very minor fix: if my understanding is correct, "trough" should be "through".

Fix typos in the tutorial

---

src/facet_components.cpp
src/vertex_components.cpp
tests/test_basic.py
tutorial/igl_docs.md

Renamed `face_components` to `facet_components`.
I don't know if this is a typo or on purpose?!
I found it quite confusing as the underlying C++ function is `igl::facet_components()`.
Also replaced reference to `face_components_from_faces` with `facet_components` as the former does not (yet?) exist.
If the PR is obsolet, it might be a good idea to add a hint somewhere.

face_components -> facet_components

---

src/readOBJ.cpp

Reading a file with varying face degree returned message "file not
found" even though the error was coming from something else.
Also fix the docstring that was incorrect.
Eventually we should fall back to the other overloads of [igl::readOBJ](https://github.com/libigl/libigl/blob/master/include/igl/readOBJ.h#L44)
(potentially adding an optional argument to read_obj).
Suggested fix to #71

Fix misleading error message when reading OBJ

---

src/adjacency_matrix.cpp
src/include/common.h
tests/test_basic.py

- Added a function called `assert_valid_simplex_idxs` to ensure that an #Nx#M where #M>= 2 is provided, instead of #M==3 | #M == 4 which was a previous requirement for using `adjacency_matrix`. 
- Adjacency matrices can now be built with edge lists:
```
>>> import numpy as np
>>> import igl
>>> a = np.array([[0,1], [1,2], [2,3], [3,0]])
>>> igl.adjacency_matrix(a)
<4x4 sparse matrix of type '<class 'numpy.longlong'>'
with 8 stored elements in Compressed Sparse Column format>
```

Fixed adjacency matrix requirements for 3/4 simplices

---

azure-pipelines.yml
setup.py

The [errors](https://github.com/libigl/libigl-python-bindings/runs/5103264270) were:
- Use obsoleted python 3.5, [see](https://endoflife.date/python)
- Sometimes, `os.environ.get("KEY")` may return NoneType 
- remove python-3.5 from `azure-piplines.yml`
- Use `os.environ.get("KEY", "")` for preventing NoneType
- Upgrade the version of OS images:
[`macos-10.13` -> `macos-10.15`](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
[`vs2017-win2016` -> `windows-2019`](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/)
CI build Result: https://dev.azure.com/n66/PublicCI/_build/results?buildId=114&view=results
@teseoch

Fixed CI build

---

setup.py

The default for parallel build was previous 2 cores. I've increased to 8 (I believe this will better match the common case). Meanwhile, I added a param via environment variables to change as needed (mirroring how pytorch controls this). Anyone can do:
```
MAX_JOBS=64 python setup.py install
```

increase j2->j8 ; allow env override MAX_JOBS

---

mkdocs.yml

Per https://www.mkdocs.org/user-guide/configuration/#edit_uri. Although edit_uri is auto derived on github, it points to edit/master/docs/, not edit/master/tutorial/

fix the edit button in the documentation

---

tests/test_basic.py

Should write tests for all of the cgal functions. This one got lost in the shuffle.

Restore cgal test (`test_convex_hull`)

---

cmake/PyiglDependencies.cmake
src/copyleft/cgal/convex_hull.cpp

copy was needed before libigl fix https://github.com/libigl/libigl/pull/1989

Remove unnecessary copy

---

.github/workflows/wheels.yml
CMakeLists.txt
classes/AABB.cpp
classes/classes.cpp
src/in_element.cpp
tests/test_basic.py

Fixes https://github.com/libigl/libigl-python-bindings/issues/150
As much as I'd like to have as close as possible match in python binding names to igl function names, I'm not sure what to do about `igl::AABB` which is templated on `int DIM` for the dimension and dependent functions like `igl::in_element` which take an `AABB` instance as an argument. In this PR, I introduce two wrappers `in_element_2` and `in_element_3` which correspond to `in_element` called with a 2D and 3D `AABB` class respectively.
In turn, I've also introduced the `AABB` class, which (like all bound classes?) only works for `Eigen::MatrixXd` and `Eigen::MatrixXi` inputs. Despite this inelegance, `squared_distance` member function is, I think, a good example of how to use `std::variant` to achieve pythonic variable …

Basic AABB support; in_element; (req C++17)

---

scripts/blender_igl_export.py

I created a deformable mesh with a skeleton and it's corresponding skinning weights in blender. However, I wasn't able to find any tooling to export libigl compatible assets. 
So I created this script to export 
- obj that exports mesh compatible with libigl's read_obj function
- tgf that exports skeleton hierarchy compatible with libigl's read_tgf function
- dmat that exports skinning weights compatible with libigl's read_dmat function
1. In the scripting tab of the Blender layout, load the blender_script_export.py 
2. Select the parent Armature in the scene inspector of the editor 
Key Notes: 
a. The armature used for rigging needs to match the name of the parent selected for export.
b. It's best to set the highest level bone of the armature as "root". If you intend to use a different …

Adding a script to export igl assets from blender

---

src/writeMSH.cpp
tests/test_basic.py

Fixes #197 for the most part. The *Fields* are not supported because of the std::vector<MatrixXd> implementation. Perhaps waiting on https://github.com/fwilliams/numpyeigen/issues/65

writeMSH binding

---

cmake/PyiglDependencies.cmake
igl/_version.py

forgot to rename branch but this is bumping libigl to 2.5.0
Will upload CI wheels to pypi upon success.

bump libigl to v2.5.0

---

.github/workflows/wheels.yml

Fixes #221. Have tested in CI on my own fork and appears to work. Not sure exactly what was required, but I've made the CI generally more readable, and updated versions of actions.

Fix wheel building for `3.12`

---

tutorial/igl_docs.md

Hi,
I just noticed that the ```polygon_mesh_to_triangle_mesh``` and ```polygon_mesh_to_triangle_mesh_from_list``` functions are not available as Python bindings, so they should probably be removed from the docs to avoid confusion?

Remove nonexistent functions from docs

---

.github/workflows/wheels.yml

This pull request includes a small but important update to the `.github/workflows/wheels.yml` file. The change updates the version of the `cibuildwheel` package used in the workflow.
* [`.github/workflows/wheels.yml`](diffhunk://#diff-75627befeafda60a526c116b32f6fdef9bf57bcf456f840d7592c1d6f13facb4L50-R50): Updated `cibuildwheel` package from version `2.22.0` to `2.23.0`.

bump cibuildhweel

---

CMakeLists.txt
README.md
src/copyleft/cgal/remesh_self_intersections.cpp
src/sparse_map_noop.cpp
src/sparse_map_shape.cpp
src/sparse_noop.cpp
src/sparse_shape.cpp
test_sparse.py

to handle sparsematrix more efficiently

[WIP] bump nanobind to PR

---

src/offset_surface.cpp
tests/test_all.py

This MR adds a binding for `igl::offset_surface`.

Add binding for offset_surface()

---

src/harmonic.cpp
tests/test_all.py

Hi,
Was updating some dependencies for a project and noticed that 'harmonic_integrated_from_laplacian_and_mass' was missing from the new bindings, so I've added it here (with a basic unit test). I've kept it as the same name in the docs (rather than overloading 'harmonic' like the c++ does for consistency with past versions), but happy to change it.

Add binding for harmonic_integrated_from_laplacian_and_mass
